name : Share data between multiple job

on : push

jobs:
    Build-01:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.0
            
            - name : Install cow-say
              run : sudo apt install cowsay -y
              
            - name: Executing cmd command
              run : dragon "Hey rushabh learning GitHub Actions be aware" > dragon.txt 
              
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.4.0
              with: 
                name: Uploading Dragon.txt
                path : dragon.txt
              
    Test-02:
        runs-on: ubuntu-latest
        needs: Build-01
        steps:

            - name: Download a Build Artifact
              uses: actions/download-artifact@v4.1.8
              with: 
                name: dragon.txt
                  
            - name : Check file
              run : grep -i "rushabh" dragon.txt 
    
    Deploy-03:
        runs-on: ubuntu-latest
        needs: [Test-02,Build-01]
        steps:
            - name: Download a Build Artifact
              uses: actions/download-artifact@v4.1.8
              with: 
                name: dragon.txt

            - name : Run Script
              run : grep -i "rushabh" dragon.txt

            - name : cat file
              run: cat dragon.txt