name: build

on:
  workflow_dispatch: 
  push:

jobs:
  build:
    name: build
    runs-on: windows-2012
    steps:
      - uses: actions/checkout@v4

       
      - name : print dotnet version
        run : |
            dotnet --version
            dotnet --list-runtimes
            dotnet --list-sdks
