name: build

on:
  workflow_dispatch: 

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # .NET Framework 4.5 is pre-installed on windows-latest, no need to setup explicitly
      - name : print dotnet version
        run : dotnet --version

      - name: Install NuGet
        run: nuget restore
