name : My first action

on : push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome & Update - Upgrade
              run : |
                echo "Hello ! Rushabh Welcome"
                sudo apt update -y
                sudo apt upgrade -y 

            - name : Gnerate Ascii Work    
              run : | 
               cowsay -f dragon "Rushabh is learning GitHub Actions and will soon do automation"
                 
            # - name: apt update
            #   run : sudo apt update 
            
            # - name: apt upgrade
            #   run : sudo apt upgrade
            
            - name: print Os name
              run: cat /etc/os-release

            - name: Checkout
              uses: actions/checkout@v4.2.0
          
            - name : List all files & Print Read me 
              run: |
                ls
                cat README.md
                echo "=================================== Bye ! We are sad to see you go.  =================================== "

            # - name: printing file content
            #   run: cat README.md

            # - name : Exit Text
            #   run: echo "=================================== Bye ! We are sad to see you go.  =================================== "

            