name : My first action

on : push

jobs: 
    ascii_job :
        runs-on : ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4.2.0

            - name : Install COW-SAY
              run : sudo apt install cowsay -y
            
            - name: Execute Cowsay in cmd
              run : cowsay -f dragon "Hey rushabh learning GitHub Actions be aware" > dragon.txt

            - name: test file exists
              run : grep -i "dragon" dragon.txt

            - name : Read file
              run : cat dragon.txt

            - name: list all files
              run : | 
                ls -lrta
                echo "Exiting action workflow"