name : multiple job

on : push

jobs:
    Build-01:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.0
            
            - name : Install cow-say
              run : sudo apt install cowsay -y
    Test-02:
        runs-on: ubuntu-latest
        needs: Build-01
        steps:
            - name : Check file
              run : grep -i "rushabh" dragon.txt 
    
    Deploy-03:
        runs-on: ubuntu-latest
        needs: [Test-02,Build-01]
        steps:

            - name : Run Script
              run : grep -i "rushabh" dragon.txt

            - name : cat file
              run: cat dragon.txt