name : Run Script 

on : push

jobs : 
    running_script:
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v4.2.0
          
          - name: execute script
            run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh
